---
- name: Install SonarQube
  hosts: Local
  remote_user : mai
  become : yes 
  
  gather_facts: false

  vars:
    ansible_host_key_checking: False
    ansible_stdout_callback: yaml

  roles : 
    - SonarQube

